name: protolude
version: 0.3.3
github: "eddiejessup/protolude"
license: BSD3
author: "Stephen Diehl"
maintainer: "elliot.marsden@gmail.com"
copyright: "Copyright (c) 2017 Stephen Diehl"
language: GHC2021

description: Please see the README on GitHub at <https://github.com/eddiejessup/protolude#readme>

dependencies:
  - base

library:
  source-dirs: src

  dependencies:
    - array                >=0.4  && <0.6
    - async                >=2.0  && <2.3
    - base                 >=4.6  && <4.18
    - bytestring           >=0.10 && <0.11.4
    - containers           >=0.5  && <0.7
    - deepseq              >=1.3  && <1.5
    - ghc-prim             >=0.3  && <0.10
    - hashable             >=1.2  && <1.5
    - mtl                  >=2.1  && <2.3
    - mtl-compat           >=0.2  && <0.3
    - stm                  >=2.4  && <2.6
    - text                 >=1.2  && <2.1
    - transformers         >=0.2  && <0.6
    - transformers-compat  >=0.4  && <0.8
    - fail ==4.9.*

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - MultiParamTypeClasses
  - OverloadedStrings
